class Movie {
  static get many => null;

  static List<Movie> getMovies() => [
        Movie(
          "Airlift",
          "2016",
          '8/10',
          '22 January 2016',
          '2hr 10min',
          'Raja Krishna Menon',
          ' Sonu Sinha',
          'Akshay Kumar , Nimrat Kaur , Lena , Avatar Gill , Gunjan Malhotra',
          'Ranjit Katiyal, an Indian businessman, leads a happy and successful life in Kuwait with his family. However, when Iraq invades Kuwait, he decides to risk his life to save his stranded countrymen.',
          'Hindi,Arabic,Malayalam',
          'Kuwait',
          'movie',
          'True',
          'Screen Awards, Zee Cine Awards, Mirchi Music Awards and many more',
          [
            'https://stat1.bollywoodhungama.in/wp-content/uploads/2016/05/438311204.jpg',
            'https://www.filmibeat.com/fanimg/airlift-photos-images-36867.jpg',
            'https://static.toiimg.com/thumb/msid-61268338,width-219,height-317,imgsize-40010/61268338.jpg',
            'https://m.media-amazon.com/images/I/71aDD7PT4QL._SL1400_.jpg',
            'https://femina.wwmindia.com/content/2020/oct/airlift71602773021.jpg',
            'https://i1.wp.com/unsungbollywood.com/wp-content/u…ational-Award-Winners.jpeg?resize=600%2C850&ssl=1',
          ],
          'https://m.media-amazon.com/images/I/71aDD7PT4QL._SL1400_.jpg',
        ),
        Movie(
          "Aiyaary",
          "2018",
          '7.9/10',
          '16 February 2018',
          '2h 37m',
          'Neeraj Pandey',
          ' Neeraj Pandey',
          'Sidharth Malhotra , Rakul Preet Singh , Manoj Bajpayee , Anupam Kher',
          'After Colonel Abhay Singh and his protege, Jai Bakshi, have a fallout, Jai goes rogue and threatens to bring down the government. Learning about this, his mentor is forced to go after him.',
          'Hindi,Arabic',
          'India',
          'movie',
          'True',
          'National Film Award for Best First Film , Screen awards',
          [
            'https://static-koimoi.akamaized.net/wp-content/new-galleries/2018/02/aiyaary-movie-review-2.jpg',
            'https://st1.bollywoodlife.com/wp-content/uploads/2017/12/aiyaary.jpg',
            'https://i2.cinestaan.com/image-bank/1500-1500/106001-107000/106949.jpg',
            'https://www.bollywoodhungama.com/wp-content/uploads/2018/02/Aiyaary-7.jpg',
            'https://www.bollywoodhungama.com/wp-content/uploads/2017/12/Aiyaary-9.jpg',
          ],
          'https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/Aiyaary_-_Poster.jpg/220px-Aiyaary_-_Poster.jpg',
        ),
        Movie(
          "Bhaag Milkha Bhaag",
          "2013",
          '8.9/10',
          '11 July 2013',
          '3h 9m',
          'Rakeysh Omprakash Mehra',
          'Prasoon Joshi',
          'Farthan Akhtar, Sonam Kapoor , Divya Dutta , Pavan Malhotra',
          'This is a true story of `the Flying Sikh- world champion runner and Olympian Milkha Singh who overcame the massacre of his family and the civil war during the India-Pakistan partition.',
          'Hindi',
          'India',
          'movie',
          'True',
          'Filmfare Award, Natinal Awards IIFA Awards and many more',
          [
            'https://i.scdn.co/image/ab67616d0000b273fd2df008046f04c32d9c0c2e',
            'https://stat1.bollywoodhungama.in/wp-content/uploads/2016/03/74637391.jpg',
            'https://i.scdn.co/image/ab67616d0000b273fd2df008046f04c32d9c0c2e',
            'https://stat1.bollywoodhungama.in/wp-content/uploads/2016/03/74637391.jpg',
            'https://i.scdn.co/image/ab67616d0000b273fd2df008046f04c32d9c0c2e',
          ],
          'https://stat1.bollywoodhungama.in/wp-content/uploads/2016/03/74637391.jpg',
        ),
        Movie(
          "Ghazi attack",
          "2017",
          '7.6/10',
          '17 February 2017',
          '2h 4m',
          'Sankalp Reddy',
          ' Gunnam Gangaraju',
          'Atul Kulkarni , Kay Kay Menon ,Taapsee Pannu , Rahul Singh',
          'In 1971, amid rising tensions between India and Pakistan over the liberation war of East Pakistan, Pakistan navy, in a top secret mission, plans an attack on Indian majestic-class aircraft carrier …',
          'Hindi, Telugu',
          'Turkey.',
          'movie',
          'True',
          'Screen Awards, Zee Cine Awards, Mirchi Music Awards and many more',
          [
            'https://www.bharathmedia.com/SiteDataStore/Posts/2017/2382/Ghazi-Attack-Movie-Review.jpg',
            'https://www.bharathmedia.com/SiteDataStore/Posts/2017/2382/Ghazi-Attack-Movie-Review.jpg',
            'https://www.bharathmedia.com/SiteDataStore/Posts/2017/2382/Ghazi-Attack-Movie-Review.jpg',
            'https://www.bharathmedia.com/SiteDataStore/Posts/2017/2382/Ghazi-Attack-Movie-Review.jpg',
            'https://www.bharathmedia.com/SiteDataStore/Posts/2017/2382/Ghazi-Attack-Movie-Review.jpg',
          ],
            'https://www.bharathmedia.com/SiteDataStore/Posts/2017/2382/Ghazi-Attack-Movie-Review.jpg',
          
        ),
        Movie(
          "Kesari",
          "2019",
          '8.5/10',
          '21 Mar 2019',
          '2hr 30min',
          'Anurag Singh',
          'Manoj Muntashir',
          'Akshay Kumar ,Parineeti Chopra , Brahma Mishra, Edward sonnenblick',
          'Havildar Ishar SIngh plays a key role in the 1897 Battle of Saragarhi, in which an army of 21 Sikhs fought against a legion of 10,000 Afghans in what is considered as one of the greatest last-stands…',
          'Hindi,Arabic',
          'Indian',
          'movie',
          'True',
          'Screen Awards, Zee Cine Awards, Mirchi Music Awards and many more',
          [
            'https://i1.wp.com/www.filmymama.com/wp-content/upl…es-of-akshay-kumar-st.jpg?resize=1024%2C576&ssl=1',
            'https://www.filmyfenil.com/wp-content/uploads/2019/03/Kesari-wallpaper.jpg',
            '	https://th.bing.com/th/id/OIP.52dZ2c7tqQOmkSDqs_0mVAAAAA?pid=ImgDet&rs=1',
            'https://4.bp.blogspot.com/-M4SqDCR1yKw/W5n834De31I…0/Kesari%2BMovie%2BFirst%2Blook%252C%2Bposter.JPG',
          ],
          'https://imgcacheblog.instube.com/2019/03/Kesari-full-movie-1.jpg',
        ),
        Movie(
          "Lakshya",
          "2004",
          '7.3/10',
          '18 Jun 2004',
          '3hr 6min',
          'Farhan Akhtar',
          'Javed Akhtar ',
          'Hrithik Roshan, Preity Zinta , Om puri, Amitabh Bachchan',
          'Karan, a spoiled teenager, joins the Indian Army on a whim but backs out when he finds a soldiers life to be difficult. When this creates conflict with his girlfriend, he reenlists and proves his…',
          'Hindi',
          'India',
          'movie',
          'True',
          'Screen Awards, Zee Cine Awards, Mirchi Music Awards and many more',
          [
            'https://th.bing.com/th/id/OIP.dA65nULJV7pxtx-VfHhBBQDhEs?pid=ImgDet&rs=1',
            'https://th.bing.com/th/id/OIP.dA65nULJV7pxtx-VfHhBBQDhEs?pid=ImgDet&rs=1',
            'https://th.bing.com/th/id/OIP.dA65nULJV7pxtx-VfHhBBQDhEs?pid=ImgDet&rs=1',
            'https://th.bing.com/th/id/OIP.dA65nULJV7pxtx-VfHhBBQDhEs?pid=ImgDet&rs=1',
            
          ],
         'https://th.bing.com/th/id/OIP.dA65nULJV7pxtx-VfHhBBQDhEs?pid=ImgDet&rs=1',
        ),
        Movie(
          "Parmanu: The Story of Pokhran",
          "2018",
          '8.6/10',
          '25 May 2018',
          '2hr 9min',
          'Abhishek Sharma',
          'Sanyuktha Chawla Sheikh',
          'John Abraham , Diana Penty , Boman Irani,Vikas Kumar',
          'Ashwat Raina and his teammates arrive in Pokhran to re-conduct a confidential nuclear test, where they face challenges from the American Lacrosse satellite and local spies.',
          'Hindi',
          'India',
          'movie',
          'True',
          'Screen Awards, Zee Cine Awards, Mirchi Music Awards and many more',
          [
            'https://www.flixwatch.co/wp-content/uploads/81005453.jpg',
            'https://th.bing.com/th/id/OIP.xXFHA6TJcGnQExHBNsjUYwHaFF?pid=ImgDet&rs=1',
            'https://th.bing.com/th/id/OIP.FJ7yIXXVLzi6-qxZlX6aqgHaEK?pid=ImgDet&rs=1',
            'https://th.bing.com/th/id/OIP.FJ7yIXXVLzi6-qxZlX6aqgHaEK?pid=ImgDet&rs=1',
            'https://static.toiimg.com/photo/64914347.cms',
          ],
          'https://www.flixwatch.co/wp-content/uploads/81005453.jpg',
        ),
        Movie(
          "Rustom",
          "2016",
          '7.5/10',
          '12 Aug 2016',
          '2hr 20m',
          'Tinu Suresh Desai.',
          'Vipul K Rawal',
          'Akshay Kumar, Ileana DCruz, Arjan Bajwa and Esha Gupta',
          'Indian Naval Officer Rustom Pavri (Akshay Kumar) is happily married to Cynthia Pavri (Ileana DCruz) in 1959. Their marriage hits the rocks when he discovers that she is having an affair with his friend Vikram Makhija (Arjan Bajwa).',
          'Hindi',
          'India',
          'movie',
          'True',
          'Screen Awards, Zee Cine Awards, Mirchi Music Awards and many more',
          [
            'https://imgcacheblog.instube.com/2020/04/Rustom-Full-Movie-Download-InsTube.jpg',
            'https://imgcacheblog.instube.com/2020/04/Rustom-Full-Movie-Download-InsTube.jpg',
            'https://imgcacheblog.instube.com/2020/04/Rustom-Full-Movie-Download-InsTube.jpg',
            'https://imgcacheblog.instube.com/2020/04/Rustom-Full-Movie-Download-InsTube.jpg',
            'https://imgcacheblog.instube.com/2020/04/Rustom-Full-Movie-Download-InsTube.jpg',
          ],
          'https://c2.staticflickr.com/8/7505/27664485340_c51e0676f7_o.jpg',
        ),
        Movie(
          "Shershaah",
          "2021",
          '9.1/10',
          '12 Aug 2021',
          '2hr 21m',
          'Vishnuvardhan',
          'Vishnuvardhan',
          'Sidharth Malhotra, Kiara Advani, Shiv Pandit Ankita Gora',
          'Vikram Batra, a young man, dreams of becoming a soldier and falls in love with Dimple. Soon after his training, he climbs the military ranks and contributes to Indias victory in the Kargil war.',
          'Hindi',
          'India',
          'movie',
          'True',
          'Screen Awards, Zee Cine Awards, Mirchi Music Awards and many more',
          [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSo4i1_vVxukNvJk1jcNBHXDzR2X4M0Sfa2aw&usqp=CAU',
            'https://otakukart.com/wp-content/uploads/2021/08/PIC-1-3.jpeg',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSo4i1_vVxukNvJk1jcNBHXDzR2X4M0Sfa2aw&usqp=CAU',
            'https://otakukart.com/wp-content/uploads/2021/08/PIC-1-3.jpeg',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSo4i1_vVxukNvJk1jcNBHXDzR2X4M0Sfa2aw&usqp=CAU',
          ],
          'https://otakukart.com/wp-content/uploads/2021/08/PIC-1-3.jpeg',
        ),
        Movie(
          "Uri: The Surgical Strike",
          "2019",
          '9/10',
          '11 January 2019',
          '2hr 21m',
          'Aditya Dhar',
          'Aditya Dhar',
          'Vicky Kaushal, Yami Gautam, Mohit Raina , Kirti Kulhari, Paresh Rawal',
          'Major Vihaan Singh Shergill of the Indian Army leads a covert operation against a group of militants who attacked a base in Uri, Kashmir, in 2016 and killed many soldiers.',
          'Hindi',
          'India',
          'movie',
          'True',
          'Screen Awards, Zee Cine Awards, Mirchi Music Awards and many more',
          [
            'https://upload.wikimedia.org/wikipedia/en/3/3b/URI_-_New_poster.jpg',
            'https://upload.wikimedia.org/wikipedia/en/3/3b/URI_-_New_poster.jpg',
            'https://upload.wikimedia.org/wikipedia/en/3/3b/URI_-_New_poster.jpg',
            'https://upload.wikimedia.org/wikipedia/en/3/3b/URI_-_New_poster.jpg',
            'https://upload.wikimedia.org/wikipedia/en/3/3b/URI_-_New_poster.jpg',
          ],
          'https://upload.wikimedia.org/wikipedia/en/3/3b/URI_-_New_poster.jpg',
        ),
      ];

  String title;
  String year;
  String rated;
  String released;
  String runtime;
  String director;
  String writer;
  String actors;
  String plot;
  String language;
  String country;
  String awards;
  String poster;
  String type;
  String response;
  List<String> images;

  Movie(
      this.title,
      this.year,
      this.rated,
      this.released,
      this.runtime,
      this.director,
      this.writer,
      this.actors,
      this.plot,
      this.language,
      this.country,
      this.type,
      this.response,
      this.awards,
      this.images,
      this.poster);
}
